const PokemonActionTypes = {
  FETCH_POKEMONS_START: "FETCH_POKEMONS_START",
  FETCH_POKEMONS_SUCCESS: "FETCH_POKEMONS_SUCCESS",
  FETCH_POKEMONS_ERREUR: "FETCH_POKEMONS_ERREUR",
  FETCH_LOAD_MORE_POKEMONS_START: "FETCH_LOAD_MORE_POKEMONS_START",
  FETCH_LOAD_MORE_POKEMONS_SUCCESS: "FETCH_LOAD_MORE_POKEMONS_SUCCESS",
  FETCH_LOAD_MORE_POKEMONS_ERREUR: "FETCH_LOAD_MORE_POKEMONS_ERREUR",
};

export default PokemonActionTypes;