const PokemonActionTypes = {
    FETCH_POKEMONS_START : 'FETCH_POKEMONS_START',
    FETCH_POKEMONS_SUCCESS : 'FETCH_POKEMONS_SUCCESS',
    FETCH_POKEMONS_ERREUR : 'FETCH_POKEMONS_ERREUR',
    SET_NEXT_LIST : 'SET_NEXT_LIST'
};

export default PokemonActionTypes;