const ContentTypes = {
    FETCH_CONTENT_START : 'FETCH_CONTENT_START',
    FETCH_CONTENT_SUCCESS : 'FETCH_CONTENT_SUCCESS',
    FETCH_CONTENT_ERREUR : 'FETCH_CONTENT_ERREUR',
    SET_MODAL_VISIBLE : 'SET_MODAL_VISIBLE',
    SET_CONTENT_VAR : 'SET_CONTENT_VAR',
    SET_CONTENT_DATA : 'SET_CONTENT_DATA',

};

export default ContentTypes;